#include "system.h"


/*
 *   COMMANDS
 */


class command_ident
{
 public:
  const char*      name;
  do_func*     function;
};


command_ident command_list [] =
{
  { "-",             do_avatar      },
  { ".",             do_speedwalk   },
  { "'",             do_say         },       
//  { ":",             do_buildchan   }, 
  { "]",             do_immtalk     },   
  { "}",             do_god         },  
  { "accounts",      do_accounts    },
  { "allegiance",    do_allegiance  },
  { "sign",          do_sign        },
  { "apply",         do_apply       },
  { "ask",           do_ask         },       
  { "auction",       do_auction     },  
  { "atalk",         do_atalk       }, 
  { "berserk",       do_berserk     },
  { "bid",           do_bid         },
  { "bite",          do_bite        },
  { "blackjack",     do_blackjack   },
  { "build",         do_build       },
  { "bury",          do_bury        },
  { "buy",           do_buy         },       
  { "calculate",     do_calculate   },
  { "call",          do_call        },
  { "camp",          do_camp        },
  { "cedit",         do_cedit       }, 
  { "gedit",         do_gedit       }, 
  { "changes",       do_changes     },
  { "chant",         do_chant       },     
  { "chat",          do_chat        },      
  { "clans",         do_clans       },
  { "close",         do_close       },    
  { "configure",     do_configure   },
  { "consent",       do_consent     },
  { "cook",          do_cook          },
  { "craft",         do_create_poison },
  { "ctell",         do_ctell         },
  { "gchat",         do_gchat         },
  { "custom",        do_custom        },    
  { "define",        do_define        },
  { "dig",           do_dig           },
  { "dip",           do_dip         },
  { "disguise",      do_disguise    },
  { "dismount",      do_dismount    },
  { "down",          do_down        },
  { "dowse",         do_dowse       },
  { "draw",          do_draw        },
  { "drink",         do_drink       },    
  { "drop",          do_drop        },     
  { "east",          do_east        },
  { "emote",         do_emote       },     
  { "empty",         do_empty       },    
  { "enter",         do_enter       },
  { "ensnare",       do_ensnare     },
  { "equipment",     do_equipment   },
  { "exits",         do_exits       },
  { "exp",           do_exp         },
  { "extract",       do_extract     },
  { "filter",        do_filter      },    
  { "forage",        do_forage      },
  { "garrote",       do_garrote     },
  { "get",           do_get         },      
  { "give",          do_give        },  
  { "gossip",        do_gossip      },    
  { "gouge",         do_gouge       },
  { "grab",           do_wear        },     
  { "gtell",         do_gtell       },     
  { "hamstring",     do_hamstring   },
  { "hardiness",     do_hardiness   },
  { "hbug",          do_hbug        },    
  { "homepage",      do_homepage    },
  { "identity",      do_identity    },  
  { "iflag",         do_iflag       },     
  { "ignite",        do_ignite      },
  { "index",         do_index       },     
  { "info",          do_info        },      
  { "introduce",     do_introduce   }, 
  { "kick",          do_kick        },       
  { "kill",          do_kill        },       
  { "knock",         do_knock       },
  { "label",         do_label       },
  { "language",      do_language    },  
  { "ledit",         do_ledit       },
//  { "lie",           do_lie         },
  { "list",          do_list        },      
  { "load",          do_load        },
  { "lset",          do_lset        },      
  { "lstat",         do_lstat       },
  { "marmor",        do_marmor      },
  { "mdesc",         do_mdesc       }, 
  { "medit",         do_medit       },
  { "meditate",      do_meditate    },  
  { "melt",          do_melt        },      
  { "melee",         do_melee       },
  { "message",       do_message     },
  { "mfind",         do_mfind       },
  { "mflag",         do_mflag       },
  { "mload",         do_mload       },
  { "mlog",          do_mlog        }, 
  { "mount",         do_mount       },     
  { "mpflag",        do_mpflag      },
  { "mreset",        do_mreset      },
  { "mset",          do_mset        },
  { "mstat",         do_mstat       }, 
  { "mwhere",        do_mwhere      },  
  { "north",         do_north       },     
  { "ooc",           do_ooc         },
  { "pbug",          do_pbug        },
  { "purchase",      do_purchase    }, 
  { "pray",          do_pray        },      
  { "prompt",        do_prompt      },
  { "ps",            do_ps          },
  { "qstat",         do_qstat       },
  { "repair",        do_repair      },    
  { "reply",         do_reply       },     
  { "reset",         do_reset       },    
  { "rest",          do_rest        },      
  { "reboot",        do_reboot      },
  { "rename",        do_rename      },    
  { "request",       do_request     },
  { "review",        do_review      },
  { "rmwhere",       do_rmwhere     },   
  { "roomlist",      do_roomlist    },
  { "rtable",        do_rtable      },
  { "rtwhere",       do_rtwhere     },
  { "say",           do_say         },       
  { "sell",          do_sell        },      
  { "shout",         do_shout       },     
  { "sit",           do_sit         },       
  { "sleep",         do_sleep       },     
  { "smoke",         do_smoke       },
  { "south",         do_south       },     
  { "speedwalk",     do_speedwalk   },
  { "split",         do_split       },
  { "spot",          do_spot        },
  { "stand",         do_stand       },     
  { "study",         do_study       },
  { "tell",          do_tell        },      
  { "to",            do_to          },
  { "typo",          do_typo        },
  { "up",            do_up          },        
  { "value",         do_value       },     
  { "vote",          do_vote        },
  { "wake",          do_wake        },      
  { "wear",          do_wear        },     
  { "west",          do_west        },      
  { "whisper",       do_whisper     },
  { "wield",         do_wear        },     
  { "yell",          do_yell        },      
 
  { "relations",     do_relations   }, 
  { "eat",           do_eat         },      
  { "fill",          do_fill        },     
  { "hold",          do_wear        },     
  { "inventory",     do_inventory   },
  { "junk",          do_junk        },     
  { "lock",          do_lock        },     
  { "open",          do_open        },     
  { "pick",          do_pick        },     
  { "put",           do_put         },      
  { "quaff",         do_quaff       },    
  { "remove",        do_remove      },   
  { "sacrifice",     do_sacrifice   },
  { "unlock",        do_unlock      },   
  { "assist",        do_assist      },     
  { "backstab",      do_backstab    },   
  { "bash",          do_bash        },      
  { "camouflage",    do_camouflage  },
  { "charge",        do_charge      }, 
  { "consider",      do_consider    },   
  { "disarm",        do_disarm      },     
  { "flee",          do_flee        },       
  { "glance",        do_glance      },     
  { "punch",         do_punch       },      
  { "rescue",        do_rescue      },     
  { "shoot",         do_shoot       },      
  { "spin",          do_spin_kick   },  
  { "throw",         do_throw       },      
  { "wimpy",         do_wimpy       },      
  { "cast",          do_cast        },
  { "sing",          do_sing        },
  { "focus",         do_focus       },     
  { "leech",         do_leech       },     
//  { "polymorph",     do_polymorph   }, 
  { "prepare",       do_prepare     },   
  { "probe",         do_probe       },     
  { "recite",        do_recite      },    
  { "spells",        do_spells      },    
  { "sweep",         do_sweep       },     
  { "switch",        do_switch      },    
  { "zap",           do_zap         },       
  { "alias",         do_alias       },     
  { "appearance",    do_appearance  },
  { "areas",         do_areas       },     
  { "befriend",      do_befriend    },  
  { "commands",      do_commands    },  
  { "compare",       do_compare     },   
  { "compile",       do_compile     },
  { "color",         do_color       },     
  { "description",   do_descript    },  
  { "help",          do_help        },      
  { "keywords",      do_keywords    },  
  { "last",          do_last        },      
  { "look",          do_look        },      
  { "motd",          do_motd        },      
  { "options",       do_options     },   
  { "peek",          do_peek        },      
  { "pets",          do_pets        },      
  { "qlook",         do_qlook       },     
  { "quests",        do_quests      },    
  { "qwho",          do_qwho        },      
  { "reputation",    do_reputation  },
  { "score",         do_score       },     
  { "socials",       do_socials     },   
  { "statistics",    do_statistics  },
  { "time",          do_time        },      
  { "who",           do_who         },       
  { "whois",         do_whois       },     
  { "mail",          do_mail        },      
  { "notes",         do_notes       },     
  { "title",         do_title       },     
  { "follow",        do_follow      },  
  { "group",         do_group       },
  { "name",          do_name        }, 
  { "order",         do_order       },
  { "delete",        do_delete      },    
  { "password",      do_password    },  
  { "quit",          do_quit        },      
  { "save",          do_save        },      
  { "balance",       do_balance     },   
  { "deposit",       do_deposit     },   
  { "withdraw",      do_withdraw    },  
  { "abilities",     do_abilities   }, 
  { "appraise",      do_appraise    },  
  { "bandage",       do_bandage     },   
  { "climb",         do_climb       },     
  { "hands",         do_hands       },      
  { "hide",          do_hide        },       
  { "inspect",       do_inspect     },    
  { "practice",      do_practice    },   
  { "scan",          do_scan        },       
  { "search",        do_search      },     
  { "skin",          do_skin        },       
  { "skills",        do_skills      },     
  { "sneak",         do_sneak       },      
  { "steal",         do_steal       },      
  { "heist",         do_heist       },
  { "energize",      do_energize    },
  { "track",         do_track       },      
  { "untrap",        do_untrap      },     
  { "advance",       do_advance     },   
  { "approve",       do_approve     },   
  { "ban",           do_ban         },       
  { "beep",          do_beep        },      
  { "bamfin",        do_bamfin      },    
  { "bamfout",       do_bamfout     },   
  { "bugs",          do_bugs        },      
  { "disconnect",    do_disconnect  },
  { "identify",      do_identify    },  
  { "pardon",        do_pardon      },    
  { "reimburse",     do_reimburse   }, 
  { "where",         do_where       },     
  { "tedit",         do_tedit       },     
  { "tset",          do_tset        },     
  { "tstat",         do_tstat       },       
  { "dedit",         do_dedit       },       
  { "dflag",         do_dflag       },       
  { "dset",          do_dset        },        
  { "dstat",         do_dstat       },       
  { "rbug",          do_rbug        },        
  { "redit",         do_redit       },       
  { "rdesc",         do_rdesc       },       
  { "rflag",         do_rflag       },       
  { "rlog",          do_rlog        },        
  { "rname",         do_rname       },       
  { "rset",          do_rset        },        
  { "rstat",         do_rstat       },       
  { "odesc",         do_odesc       },   
  { "oedit",         do_oedit       },   
  { "oextra",        do_oextra      },  
  { "ofind",         do_ofind       },   
  { "oflag",         do_oflag       },   
  { "oload",         do_oload       },   
  { "olog",          do_olog        },    
  { "oset",          do_oset        },   
  { "ostat",         do_ostat       },   
  { "owhere",        do_owhere      },  
  { "opedit",        do_opedit      },  
  { "opcode",        do_opcode      },  
  { "opdata",        do_opdata      },  
  { "opstat",        do_opstat      },  
  { "opset",         do_opset       },   
  { "nowhere",       do_nowhere     },  
  { "hdesc",         do_hdesc       },   
  { "hedit",         do_hedit       },   
  { "hset",          do_hset        },    
  { "hstat",         do_hstat       },    
  { "acode",         do_acode       },   
  { "adata",         do_adata       },   
  { "aedit",         do_aedit       },   
  { "aflag",         do_aflag       },   
  { "aset",          do_aset        },    
  { "astat",         do_astat       },   
  { "mpedit",        do_mpedit      },  
  { "mpcode",        do_mpcode      },  
  { "mpdata",        do_mpdata      },  
  { "mpstat",        do_mpstat      },  
  { "mpset",         do_mpset       },   
  { "cflag",         do_cflag       },   
  { "cfwhere",       do_cfwhere     },
  { "qedit",         do_qedit       },   
  { "qflag",         do_qflag       },   
  { "qremove",       do_qremove     }, 
  { "qset",          do_qset        },    
  { "qwhere",        do_qwhere      },  
  { "shcustom",      do_shcustom    },
  { "shedit",        do_shedit      },  
  { "shflag",        do_shflag      },    
  { "affects",       do_affects     },   
  { "high",          do_high        },      
  { "level",         do_level       },     
  { "memory",        do_memory      },    
  { "move",          do_move        },      
  { "pull",          do_pull        },      
  { "push",          do_push        },      
  { "read",          do_read        },      
  { "system",        do_system      },    
  { "wanted",        do_wanted      },    
  { "whistle",       do_whistle     },   
  { "functions",     do_functions   },
  { "fwhere",        do_fwhere      },
  { "return",        do_return      },   
  { "deny",          do_deny        },     
  { "force",         do_force       },    
  { "freeze",        do_freeze      },   
  { "gecho",         do_gecho       },     
  { "god",           do_god         },      
  { "goto",          do_goto        },     
  { "holylight",     do_holylight   },
  { "immtalk",       do_immtalk     },  
  { "imprison",      do_imprison    }, 
  { "invis",         do_invis       },    
  { "lag",           do_lag         },      
  { "map",           do_map         },      
  { "peace",         do_peace       },    
  { "purge",         do_purge       },    
  { "recho",         do_recho       },    
  { "restore",       do_restore     },  
  { "rowhere",       do_rowhere     },  
  { "shutdown",      do_shutdown    }, 
  { "snoop",         do_snoop       },    
  { "slay",          do_slay        },     
  { "sset",          do_sset        },     
  { "tfind",         do_tfind       },    
  { "tinder",        do_tinder      },
  { "train",         do_train       },    
  { "transfer",      do_transfer    }, 
  { "trust",         do_trust       },    
  { "users",         do_users       },    
  { "wizlock",       do_wizlock     },  
  { "write",         do_write       }, 
  { "dance",         do_dance       },
  { "debug",         do_debug       },
  { "struggle",      do_struggle    },
  { "pstatus",       do_pstatus     },
  { "shift",         do_shift       },
  { "harvest",       do_harvest     },
  { "concoct",       do_concoct     },
  { "tnofind",       do_tnofind     },
  { "find_rflag",    do_rflag_find  },
  { "investigate",   do_investigate },
  { "qnedit",        do_qnedit      },
  { "qnset",         do_qnset       },
  { "qndesc",        do_qndesc      },
  { "qnreward",      do_qnreward    },
  { "qnrset",        do_qnrset      },
  { "qnstep",        do_qnstep      },
  { "qnsset",        do_qnsset      },
  { "synedit",       do_synedit     },
  { "synset",        do_synset      },
  { "mexplog",       do_mexplog     },
  { "fletch",        do_fletch      },
  { "scribe",        do_scribe      },
  { "fetish",        do_empower     },
  { "empower",       do_empower     },
  { "",              NULL           }
};


void init_commands( )
{
  int i, j;

  for( i = 0; i < MAX_ENTRY_COMMAND; i++ ) {
    for( j = 0; command_list[j].name[0] != '\0'; j++ ) {
      if( !strcasecmp( command_table[i].func_name, command_list[j].name ) ) {
        command_table[i].function = command_list[j].function;
        break;
      }
    }
  }

  return;
}


/*
 *   SPELLS 
 */


class spell_ident
{
 public:
  const char*       name;
  spell_func*   function;
};


spell_ident spell_list [] =
{ 
  { "acid blast",          spell_acid_blast          },
  { "acid storm",          spell_acid_storm          },
  { "alter magnetism",     spell_alter_magnetism     },
  { "armor",               spell_armor               },
  { "astral gate",         spell_astral_gate         },
//  { "augury",              spell_augury              },
  { "balm",                spell_balm                },
  { "banishment",          spell_banishment          },
  { "barkskin",            spell_barkskin            },
  { "bless",               spell_bless               },
  { "blind",               spell_blind               },
  { "blink",               spell_blink               },
  { "burning hands",       spell_burning_hands       },
  { "calm",                spell_calm                },
  { "call lightning",      spell_call_lightning      },
  { "cause critical",      spell_cause_critical      },
  { "cause light",         spell_cause_light         },
  { "cause serious",       spell_cause_serious       },
  { "chromatic orb",       spell_chromatic_orb       },
  { "conflagration",       spell_conflagration       },
  { "confuse",             spell_confuse             },
  { "construct golem",     spell_construct_golem     },
  { "create feast",        spell_create_feast        },
  { "create food",         spell_create_food         },
  { "create light",        spell_create_light        },
  { "create water",        spell_create_water        },
  { "cure blindness",      spell_cure_blindness      },
  { "cure critical",       spell_cure_critical       },
  { "cure light",          spell_cure_light          },
  { "cure poison",         spell_cure_poison         },
  { "cure serious",        spell_cure_serious        },
  { "detect invisible",    spell_detect_invisible    },
  { "displace",            spell_displace            },
  { "eagle eye",           spell_eagle_eye           },
  { "fear",                spell_fear                },
  { "find familiar",       spell_find_familiar       },
  { "fire shield",         spell_fire_shield         },
  { "fireball",            spell_fireball            },
  { "flame strike",        spell_flame_strike        },
  { "float",               spell_float               },
  { "fly",                 spell_fly                 },
  { "greater animation",   spell_greater_animation   },
  { "hallucinate",         spell_hallucinate         },
  { "harm",                spell_harm                },
  { "haste",               spell_haste               },
  { "heal",                spell_heal                },
  { "horrid wilting",      spell_horrid_wilting      },
  { "identify",            spell_identify            },
  { "invulnerability",     spell_invulnerability     },
  { "lesser summoning",    spell_lesser_summoning    },
  { "lightning bolt",      spell_lightning_bolt      },
  { "magic missile",       spell_magic_missile       },
  { "maelstrom",           spell_maelstrom           },
  { "major enchantment",   spell_major_enchantment   },
  { "mind blade",          spell_mind_blade          },
  { "minor enchantment",   spell_minor_enchantment   },
  { "neutralize",          spell_neutralize          },
  { "pass door",           spell_pass_door           },
//  { "polymorph",           spell_polymorph           },
  { "poultice",            spell_poultice            },
  { "prismic missile",     spell_prismic_missile     },
  { "protection/good",     spell_protect_good        },
  { "protection/evil",     spell_protect_evil        },
  { "recall",              spell_recall              },
  { "remove curse",        spell_remove_curse        },
  { "request ally",        spell_request_ally        },
  { "resist acid",         spell_resist_acid         },
  { "resist cold",         spell_resist_cold         },
  { "resist fire",         spell_resist_fire         },
  { "resist shock",        spell_resist_shock        },
//  { "resurrect",           spell_resurrect           },
  { "revitalize",          spell_revitalize          },
  { "sanctify",            spell_sanctify            },
//  { "scry",                spell_scry                },
  { "sense danger",        spell_sense_danger        },
  { "slay",                spell_slay                },
  { "shock",               spell_shock               },
  { "sleep",               spell_sleep               },
  { "slow",                spell_slow                },
  { "summon",              spell_summon              },
  { "surcease",            spell_surcease            },
//  { "transfer",            spell_transfer            }, 
  { "restoration",         spell_restoration         }, 
  { "turn undead",         spell_turn_undead         },
  { "vitality",            spell_vitality            },
  { "water breathing",     spell_water_breathing     },
  { "web",                 spell_web                 },
  { "acid arrow",          spell_acid_arrow          },
  { "youth",               spell_youth               },

  { "holy wrath",          spell_holy_wrath          },
  { "tame",                spell_tame                },
  { "faerie fire",         spell_faerie_fire         },
  { "invisibility",        spell_invisibility        },
  { "protection plants",   spell_protection_plants   },
  { "curse",               spell_curse               }, 
  { "mists of sleep",      spell_mists_sleep         },
  { "poison cloud",        spell_poison_cloud        },
  { "magic mapping",       spell_magic_mapping       },
  { "amnesia",             spell_amnesia             },
  { "detect hidden",       spell_detect_hidden       },
  { "detect good",         spell_detect_good         },
  { "detect evil",         spell_detect_evil         },
  { "ignite weapon",       spell_ignite_weapon       },
  { "chain lightning",     spell_chain_lightning     },
  { "infravision",         spell_infravision         },
  { "mystic shield",       spell_mystic_shield       },
  { "animate dead",        spell_animate_dead        },
  { "ogre strength",       spell_ogre_strength       },
  { "silence",             spell_silence             },
  { "drain life",          spell_drain_life          },
  { "blinding light",      spell_blinding_light      },
  { "gift of tongues",     spell_gift_of_tongues     },
  { "protect life",        spell_protect_life        },
  { "true sight",          spell_true_sight          },
  { "sense life",          spell_sense_life          },
  { "detect magic",        spell_detect_magic        },
  { "continual light",     spell_continual_light     },
  { "cure disease",        spell_cure_disease        },
  { "animate clay",        spell_animate_clay        },
  { "freeze",              spell_freeze              },
  { "chilling touch",      spell_chilling_touch      },
  { "ice storm",           spell_ice_storm           },
  { "replicate",           spell_replicate           },
  { "thorn shield",        spell_thorn_shield        },
  { "group serious",       spell_group_serious       },
  { "group critical",      spell_group_critical      },
  { "ion shield",          spell_ion_shield          },
  { "meteor swarm",        spell_meteor_swarm        },
  { "ice lance",           spell_ice_lance           },
  { "purify",              spell_purify              },
//  { "wither",              spell_wither              },
  { "obscure",             spell_obscure             },
  { "conjure elemental",   spell_conjure_elemental   },
  { "find mount",          spell_find_mount          },
//  { "hawks view",          spell_hawks_view          },
  { "companion strength",  spell_companions_strength },
  { "briartangle",         spell_briartangle         },
  { "ironskin",            spell_ironskin            },
  { "gem burst",           spell_gem_burst           },
  { "hoar frost",          spell_hoar_frost          },
  { "vigor",               spell_vigor               },
  { "gryphon watch",       spell_gryphons_watch      },
  { "universal gate",      spell_universal_gate      },
  { "restore item",        spell_restore_item        },
  { "earthquake",          spell_earthquake          },
  { "holy aura",           spell_holy_aura           },
  { "unholy aura",         spell_unholy_aura         },
  { "greater summon",      spell_greater_summon      },
  { "unceasing vigilance", spell_unceasing_vigilance },
  { "holy word",           spell_holy_word           },
  { "unholy word",         spell_unholy_word         },
  { "holy flail",          spell_holy_flail          },
  { "unholy flail",        spell_unholy_flail        },
  { "lesser mount",        spell_lesser_mount        },
  { "divine might",        spell_divine_might        },
  { "greater mount",       spell_summon_dragon       },
  { "disperse undead",     spell_disperse_undead     },
  { "bone dart",           spell_bone_dart           },
  { "skull watch",         spell_skull_watch         },
  { "gift of the night",   spell_gift_night          },
  { "blight",              spell_blight              },
  { "ghost armor",         spell_ghost_armor         },
  { "bone wrench",         spell_bone_wrench         },
  { "starving madness",    spell_starving_madness    },
  { "doom",                spell_doom                },
  { "ghost chains",        spell_ghost_chains        },
  { "withering flesh",     spell_withering_flesh     },
  { "summon cadaver",      spell_summon_cadaver      },
  { "shield of bones",     spell_shield_bones        },
  { "mind crush",          spell_mind_crush          },
  { "weapon blight",       spell_weapon_blight       },
  { "destructive touch",   spell_destructive_touch   },
  { "bane",                spell_bane                },
  { "mind destruction",    spell_mind_destruction    },
  { "shuddering touch",    spell_shuddering_touch    },
  { "dead man eyes",       spell_dead_man_eyes       },
  { "soul tear",           spell_soul_tear           },
  { "summon undead",       spell_summon_undead       },
  { "death mask",          spell_death_mask          },
  { "volley of bones",     spell_volley_bones        },
  { "blood bond",          spell_blood_bond          },
  { "death skin",          spell_death_skin          },
  { "desolation",          spell_desolation          },
  { "bane fiend",          spell_bane_fiend          },
  { "forsaken",            spell_forsaken            },
  { "feast of life",       spell_feast_life          },
  { "mind blank",          spell_mind_blank          },
  { "blessing of Taraskatt",  spell_bless_taraskatt     },
  { "unholy fire",         spell_unholy_fire         },
  { "lichdom",             spell_lichdom             },
  { "mind snap",           spell_mind_snap           },
  { "decaying touch",      spell_decaying_touch      },
  { "feast of the dead",   spell_feast_of_dead       },
  { "skin of the cadaver", spell_skin_of_cadaver     },
  { "skin wrench",         spell_skin_wrench         },
  { "dark chill",          spell_dark_chill          },
  { "gloom",               spell_gloom               },
  { "corpse light",        spell_corpse_light        },
  { "walk of the damned",  spell_walk_damned         },
  { "return the dead",     spell_return_the_dead     },
  { "blood fiend",         spell_blood_fiend         },
  { "corpse harvest",      spell_corpse_harvest      },
  { "ghost shield",        spell_ghost_shield        },
  { "demon shield",        spell_demon_shield        },
  { "body rot",            spell_body_rot            },
  { "ethereal bridge",     spell_ethereal_bridge     },
  { "shatter resolve",     spell_shatter_resolve     },
  { "liquify bones",       spell_liquify_bones       },
  { "mind blow",           spell_mind_blow           },
  { "enfeeblement",        spell_enfeeblement        },
  { "simulcrum",           spell_simulcrum           },
  { "humming toad call",   spell_toad                },
  { "song of the brook",   spell_brook               },
  { "chant of war",        spell_war                 },
  { "song of summer",      spell_summer              },
  { "song of winter",      spell_winter              },
  { "song of the wheat",   spell_wheat               },
  { "chant of battle",     spell_battle              },
  { "song of the buck",    spell_buck                },
  { "song of serenity",    spell_serenity            },
  { "song of shadow",      spell_shadow              },
  { "bark of the wolf",    spell_bark_wolf           },
  { "howl of the wolf",    spell_howl_wolf           },
  { "baleful howl",        spell_bale_howl           },
  { "harpy screech",       spell_harpy_screech       },
  { "song of autumn",      spell_autumn              },
  { "song of the summer equinox", spell_summer_equinox },
  { "song of the winter equinox", spell_winter_equinox },
  { "song of seasons mastery", spell_seasons_mastery },
  { "song of the mire",        spell_mire                },
  { "song of the quicksand",   spell_quicksand           },
  { "song of carnage",     spell_carnage             },
  { "song of eternal battle", spell_eternal_battle   },
  { "song of blurring blades", spell_blurring      },
  { "song of the tireless traveller", spell_tireless },
  { "song of the ox",      spell_ox                  },
  { "song of the seraphim", spell_seraphim           },
  { "song of the swift",   spell_swift               },
  { "song of the walrus",  spell_walrus              },
  { "song of the celestial", spell_celestial         },
  { "song of the cheetah", spell_cheetah             },
  { "song of the river",   spell_river               },
  { "song of the harvest", spell_harvest             },
  { "song of renewal",     spell_renewal             },
  { "song of spring",      spell_spring              },
  { "natures blessing",    spell_natures_blessing    },
  { "natures imbued",      spell_natures_imbued      },
  { "natures infuse",      spell_natures_infuse      },
  { "natures spirit",      spell_natures_spirit      },
  { "natures calling",     spell_natures_calling     },
  { "calling of the true beast", spell_calling_beast },
  { "souls balm",          spell_souls_balm          },
  { "souls respite",       spell_souls_respite       },
  { "souls recovery",      spell_souls_recovery      },
  { "souls return",        spell_souls_return        },
  { "deaths recall",       spell_deaths_recall       },
  { "body snatch",         spell_body_snatch         },
  { "summon corpse",       spell_summon_corpse       },
  { "theft of death",      spell_theft_of_death      },
  { "scream of the banshee", spell_wail_banshee      },
  { "wail of the banshee", spell_wail_mourning       },
  { "wail of the siren",   spell_sirens_cry          },
  { "song of the serenade",spell_serenade            },
  { "lullaby",             spell_lullaby             },
  { "song of the enchanted sleep",spell_enchanted_sleep                 },
  { "song of the dragons stance",spell_dragons_stance },
  { "song of the bears stance",spell_bears_stance                 },
  { "song of the swirling blades",spell_swirling_blades                 },
  { "song of iron resolve",spell_iron_resolve                 },
  { "song of whirling death",spell_whirling_death                 },
  { "song of the cats stance", spell_cats_stance                 },
  { "shield of flame",     spell_flame_shield        },
  { "fiery shield",        spell_fiery_shield        },
  { "shield of the inferno", spell_inferno_shield    },
  { "frost shield",        spell_frost_shield        },
  { "hoar shield",         spell_hoar_shield         },
  { "absolute zero",       spell_absolute_zero       },
  { "spark shield",        spell_spark_shield        },
  { "shock shield",        spell_shock_shield        },
  { "shield of lightning", spell_lightning_shield    },
  { "shield of erosion",   spell_erosion_shield      },
  { "shield of corrosion", spell_corrosive_shield    },
  { "caustic shield",      spell_caustic_shield      },
  { "song of the spring equinox",spell_spring_equinox                 },
  { "song of the harvest equinox", spell_harvest_equinox                 },
  { "evil aura",           spell_evil_aura           },
  { "dreadful aura",       spell_dreadful_aura       },
  { "wicked aura",         spell_wicked_aura         },
  { "blessed aura",        spell_blessed_aura        },
  { "hallowed aura",       spell_hallowed_aura       },
  { "saintly aura",        spell_saintly_aura        },
  { "bone prison",         spell_bone_prison         },
  { "life tap",            spell_life_tap            },
  { "wraith form",         spell_wraith_form         },
  { "autumn touch",        spell_autumn_touch        },
  { "winters gale",        spell_winters_gale        },
  { "winters touch",       spell_winters_touch       },
  { "hail stones",         spell_hail_stones         },
  { "summer touch",        spell_summer_touch        },
  { "dancing tallow",      spell_dancing_tallow      },
  { "harness the winds",   spell_harness_winds       },
  { "green finger",        spell_green_finger        },
  { "natures boon",        spell_natures_boon        },
  { "tree form",           spell_tree_form           },
  { "parching grasp",      spell_parching_grasp      },
  { "entangle",            spell_entangle            },
  { "natures fury",        spell_natures_fury        },
  { "natures shielding",   spell_natures_shielding   },
  { "defoliation",         spell_defoliation         },
  { "breath of the ice serpent", spell_breath_serpent },
  { "trail blaze",         spell_trail_blaze         },
  { "path find",           spell_path_find           },
  { "caress of nature",    spell_caress_nature       },
  { "gift of the bear",    spell_bears_gift          },
  { "gift of the snake",   spell_snakes_gift         },
  { "gift of the lion",    spell_lions_gift          },
  { "caress of gaia",      spell_caress_gaia         },
  { "gift of the hawk",    spell_hawks_gift          },
  { "gift of the wyrm",    spell_wyrms_gift          },
  { "wilderness lore",     spell_wilderness_lore     },
  { "animal companion",    spell_animal_companion    },
  { "bramble skin",        spell_bramble_skin        },
  { "thistle skin",        spell_thistle_skin        },
  { "gift of the owl",     spell_owls_gift           },
  { "lashing frogs tongue",spell_frog_tongue         },
  { "pool of bubbling water",spell_acidic_water      },
  { "acid rain",          spell_acid_rain            },
  { "touch of the electric eel", spell_electric_eel  },
  { "electrical storm",    spell_electrical_storm    },
  { "bite of the fire ant",spell_fire_ant            },
  { "river of magma",      spell_river_magma         },
  { "circle of healing",   spell_circle_healing      },
  { "druidic ring",        spell_druidic_ring        },
  { "good berry",          spell_good_berry          },
  { "deep energy",         spell_deep_energy         },
  { "tree gate",           spell_tree_gate           },
  { "blessed fruit",       spell_blessed_fruit       },
  { "gift of the land",    spell_gift_of_the_land    },
  { "caress of spring",    spell_caress_of_spring    },
  { "breath of life",      spell_breath_of_life      },
  { "embrace of the world",spell_embrace_of_the_world},
  { "water walk",          spell_water_walk          },
  { "wind walk",           spell_wind_walk           },
  { "obscuring mist",      spell_obscuring_mist      },
  { "poison touch",        spell_poison_touch        },
  { "insect plague",       spell_insect_plague       },
  { "spike growth",        spell_spike_growth        },
  { "whirlwind",           spell_whirlwind           },
  { "summon swarm",        spell_summon_swarm        },
  { "sunburst",            spell_sunburst            },
  { "shillelagh",          spell_shillelagh          },
  { "firefly",             spell_firefly             },
  { "natures health",      spell_natures_health      },
  { "companion health",    spell_companion_health    },
  { "natures restoration", spell_natures_restoration },
  { "touch of healing",    spell_touch_healing       },
  { "inferno",             spell_inferno             },
  { "solid",               spell_solid               },
  { "static charge",       spell_static_charge       },
  { "withering blast",     spell_withering_blast     },
  { "uspell_353",          spell_bug                 },
  { "uspell_354",          spell_bug                 },
  { "uspell_355",          spell_bug                 },
  { "uspell_356",          spell_bug                 },
  { "uspell_357",          spell_bug                 },
  { "uspell_358",          spell_bug                 },
  { "uspell_359",          spell_bug                 },
  { "uspell_360",          spell_bug                 },
  { "uspell_361",          spell_bug                 },
  { "uspell_362",          spell_bug                 },
  { "uspell_363",          spell_bug                 },
  { "uspell_364",          spell_bug                 },
  { "uspell_365",          spell_bug                 },
  { "uspell_366",          spell_bug                 },
  { "uspell_367",          spell_bug                 },
  { "uspell_368",          spell_bug                 },
  { "uspell_369",          spell_bug                 },
  { "uspell_370",          spell_bug                 },
  { "uspell_371",          spell_bug                 },
  { "uspell_372",          spell_bug                 },
  { "uspell_373",          spell_bug                 },
  { "uspell_374",          spell_bug                 },
  { "uspell_375",          spell_bug                 },
  { "uspell_376",          spell_bug                 },
  { "uspell_377",          spell_bug                 },
  { "uspell_378",          spell_bug                 },
  { "uspell_379",          spell_bug                 },
  { "uspell_380",          spell_bug                 },
  { "uspell_381",          spell_bug                 },
  { "uspell_382",          spell_bug                 },
  { "uspell_383",          spell_bug                 },
  { "uspell_384",          spell_bug                 },
  { "uspell_385",          spell_bug                 },
  { "uspell_386",          spell_bug                 },
  { "uspell_387",          spell_bug                 },
  { "uspell_388",          spell_bug                 },
  { "uspell_389",          spell_bug                 },
  { "uspell_390",          spell_bug                 },
  { "uspell_391",          spell_bug                 },
  { "uspell_392",          spell_bug                 },
  { "uspell_393",          spell_bug                 },
  { "uspell_394",          spell_bug                 },
  { "uspell_395",          spell_bug                 },
  { "uspell_396",          spell_bug                 },
  { "uspell_397",          spell_bug                 },
  { "uspell_398",          spell_bug                 },
  { "uspell_399",          spell_bug                 },
  { "",                    NULL                      }
};


void init_spells( )
{
  int i, j;

  for( i = 0; i < SPELL_COUNT; i++ ) {
    spell_table[i].function = NULL; 
    for( j = 0; spell_list[j].name[0] != '\0'; j++ ) {
      if( !strcasecmp( spell_table[i].name, spell_list[j].name ) ) {
        spell_table[i].function = spell_list[j].function;
        break;
      }
    }
    if( spell_table[i].function == NULL ) 
      panic( "Init_Spells: Null function - %s", spell_table[i].name );
  }

  return;
}


